### ISSUE TITLE
Not working with "sub" emails

### ISSUE THREAD

**Issue by erralb** [WordImpress/woocommerce-preview-emails#10]
Hi I am using this WooCommerce plugin https://wordpress.org/plugins/woocommerce-quick-donation/

With this plugin it is possible to override the templates by placing a "donation" folder into the "woocommerce" folder placed in the theme.

Do you think it would be possible to extend your script in order to preview emails from WooCommerce plugins?

**Comment by mathetos** [comment]
My guess (since I'm not familiar with that plugin) is no. Unless that plugin creates it's own unique email type that is templateable just like the other native WooCommerce emails are. This script loads all the emails that are registered, so if it did that they would show up correctly. But most likely it just passes the standard information to the standard email.

Also, you should checkout Give for donations. We're the developers and we think it's the best way to do donations in WordPress: https://givewp.com

Thanks!

**Comment by erralb** [comment]
Actually this plugin is creating its own email templates like WooCommerce does.
It's ok I will try to fork your plugin and make it work, no worries.

I know givewp, it's a nicew project but too many addons, too expensive... not managing scheduled and recurring payments, not offering enough payment systems. WC Quick Donation, being base on WooCommerce, can make use of all the WooCommerce plugins...

Thanks for you answer!
