### ISSUE TITLE
Clunky install.

### ISSUE THREAD

**Issue by louiswalch** [WordImpress/woocommerce-preview-emails#18]
This looks like a great plugin to save time and headache when customizing WC emails. The install seems a bit clunky/hacky however. Why not release as a Woocommerce Extension or Wordpress Plugin? Trying to offer insight, not back-seat coding.

Also, as I have customized my `email-header.php` file, there would be collision with that file. Could you use a hook to inject your custom code?

**Comment by mathetos** [comment]
I could, but the purpose of this library wasn't simply the feature, it was also a tutorial on how to fully customize your WooCommerce emails. That's why I took this approach and don't plan on changing it.

Here's the full article:
https://wordimpress.com/customize-and-preview-woocommerce-emails/

Thanks!
