### ISSUE TITLE
wc_get_template in email-header.php

### ISSUE THREAD

**Issue by danielvonmitschke** [WordImpress/woocommerce-preview-emails#3]
Shouldn't wc_get_template() be called AFTER the if condition?
otherwise it will be printed in every sent email and I think we don't need that (though it wouldn't do any damage).

**Comment by danielvonmitschke** [comment]
Same question for "@import url(http://fonts.googleapis.com/css?family=Lato:400,900);".
actually the whole style-block could/should be wrapped in the if-condtion.

**Comment by mathetos** [comment]
Regarding wc_get_template(), no because that is how Woo injects the styles into the email template.

Regarding the @import I would have thought the same, but it's not totally clear to me why:
1) When @import is put inside the conditional it doesn't work correctly when previewing emails
and
2) Why when it's OUTSIDE the conditional it actually doesn't output in the email at all. I've tested it several times.
