### ISSUE TITLE
Blank Email Header

### ISSUE THREAD

**Issue by Dooza** [WordImpress/woocommerce-preview-emails#4]
Not sure if this is intentional or not, but the header in the email is always blank when previewing.

**Comment by mathetos** [comment]
Can you provide a screenshot? And which version of WooCommerce are you working on? Are you certain that the required files are included correctly? A little more detail and I can help better. Thanks!

**Comment by Dooza** [comment]
Woocommerce 2.3.10. I have uploaded the files, added the call in the themes function.php file. Its mostly fine, here is the screenshot.

![customer-invoice](https://cloud.githubusercontent.com/assets/9673250/7985990/a90a6df8-0acc-11e5-868c-80fda49b8e07.jpg)

The emails send with the header, its only in preview they are empty. It also seems to show the shipping information twice, but I can live with that.

**Comment by Dooza** [comment]
Your screenshot on the main page also shows an empty header :)

**Comment by Dooza** [comment]
When I say header I mean the coloured bar (in my case yellow) which should have the message from the email settings.

**Comment by mathetos** [comment]
Ah yes. It's not on purpose but it's unavoidable because of the way that message is input into the header. But try installing a useful plugin called "Email Cop". This will stop all emails from leaving your site, and give you a link to preview them. When you do that, you'll see that the header information shows up no problem. Wish there was a way to get that info in there, but for now, that's how it is.
